### ISSUE TITLE
casino issue

### ISSUE THREAD

**Issue by KittyPark** [shinhan-casino/pig-dice-game#2]
## 요약
카지노 피그 다이스 게임 만들기

## 할일

팀장님
- [x] 주사위 Roll 함수 만들기
- [x] stop 함수 만들기
- [x] 1나오면 다음턴으로 넘어가는거
팀원님
- [x] 플레이어 저장하는 함수 만들기
- [x]  딜러 알고리즘

**Comment by datadbs** [comment]
+ 쌓인 점수 추가하기

**Comment by kingwangzzang1234** [comment]
각 할 일들이 하나의 이슈카드를 가지고 더 디테일한 설명이 되어야 일 하기 쉬워집니당:)
